#!/usr/bin/env python3
"""
Reads UI build artifacts and generates a C++ header with the files
embedded as byte arrays. This allows the final binary to serve the
UI without external files -- matching Tauri's asset embedding model.
"""

import os
import sys


def to_c_array(data: bytes, var_name: str) -> str:
    """Convert raw bytes into a C unsigned char array literal."""
    lines = []
    lines.append(f"static const unsigned char {var_name}[] = {{")
    for i in range(0, len(data), 16):
        chunk = data[i : i + 16]
        hex_vals = ", ".join(f"0x{b:02x}" for b in chunk)
        lines.append(f"    {hex_vals},")
    lines.append("};")
    lines.append(f"static const unsigned int {var_name}_LEN = {len(data)};")
    return "\n".join(lines)


def main():
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <ui-dist-dir> <output-header>", file=sys.stderr)
        sys.exit(1)

    dist_dir = sys.argv[1]
    output_path = sys.argv[2]

    index_html = os.path.join(dist_dir, "index.html")
    if not os.path.isfile(index_html):
        print(f"Error: {index_html} not found. Build the UI first.", file=sys.stderr)
        sys.exit(1)

    with open(index_html, "rb") as f:
        html_bytes = f.read()

    header = [
        "#pragma once",
        "// Auto-generated by embed_assets.py -- do not edit",
        "",
        to_c_array(html_bytes, "LUMINA_INDEX_HTML"),
        "",
    ]

    # Embed any additional JS/CSS assets found alongside index.html
    assets_dir = os.path.join(dist_dir, "assets")
    if os.path.isdir(assets_dir):
        for fname in sorted(os.listdir(assets_dir)):
            fpath = os.path.join(assets_dir, fname)
            if not os.path.isfile(fpath):
                continue
            safe_name = "LUMINA_ASSET_" + fname.upper().replace(".", "_").replace("-", "_")
            with open(fpath, "rb") as f:
                header.append(to_c_array(f.read(), safe_name))
                header.append("")

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        f.write("\n".join(header))

    print(f"Embedded {index_html} -> {output_path}")


if __name__ == "__main__":
    main()
